### ISSUE TITLE
Client.upload_media documentation is confusing

### ISSUE THREAD

**Issue by nex3** [tootsuite/mastodon-api#1]
The [API documentation for `Client.upload_media`](http://www.rubydoc.info/gems/mastodon-api/Mastodon/REST/Media#upload_media-instance_method) doesn't indicate the parameter type for the `file` parameter. This is especially troublesome since it needs to be the special `HTTP::FormData::File` type or the request will fail in mysterious ways.

**Comment by muffinista** [comment]
FYI, I cleaned this up a bit in a04f8aaa4425ccc1f1d6a0e4b6a266adbe835920. `upload_media` will take a `File`, `StringIO` or `HTTP::FormData::File` now and the docs should be doing a better job of explaining that.
