### ISSUE TITLE
Notifications missing from Rubygems gem

### ISSUE THREAD

**Issue by skddc** [tootsuite/mastodon-api#28]
I stumbled upon this weird issue: in this repo, which has the same version number set as the gem from Rubygems, there's a method for retrieving notifications. In my installed version 1.1.0, that file doesn't exist.

Is this actually the correct, up-to-date source code for the published gem?

**Comment by muffinista** [comment]
I don't think there's been a new gem release in a little while, but you can put this in a Gemfile to run the newest version of the code from this repo:

```
gem 'mastodon-api', require: 'mastodon'
```

**Comment by skddc** [comment]
Thanks. That's what I did, but I'm asking about the actual version of the gem not being the same as the one here.

If it's that outdated, then why not publish whatever is in `master` now?

**Comment by muffinista** [comment]
I can think of lots of reasons, but I can't publish it at all in the first place, that's a question for @Gargron
