### ISSUE TITLE
Array parameters are defined incorrectly

### ISSUE THREAD

**Issue by nex3** [tootsuite/mastodon-api#3]
[In `REST::Utils`](https://github.com/Gargron/mastodon-api/blob/master/lib/mastodon/rest/utils.rb#L36), it seems that array parameters are defined as `key[0]`, `key[1]`, and so on. This doesn't match [the expected format](https://github.com/Gargron/mastodon/issues/185#issuecomment-262211907), and seems to cause the server to ignore the array entirely.

**Comment by Gargron** [comment]
Does it actually make the server ignore the array entirely though? `key[]` and `key[0]` should be equivalent as far as I'm aware, it's just not possible to have a hash with multiple identical keys in Ruby

**Comment by nex3** [comment]
I'm pretty sure this didn't work with my experimentation last night, but it's possible something else was wrong as well.

**Comment by sull** [comment]
i'm bumping into this issue too. tried variations and getting media attached to posts has only been randomly successful. most of time the media_ids array is ignored.

**Comment by noraworld** [comment]
As @Gargron says, a hash cannot have multiple identical keys. So, this problem cannot be resolved with a hash.

I sent a pull request #30 to change a hash to an array, referring to httprb/http#419.

**Comment by chessguy** [comment]
This is more relevant to the merged response.  You can write it this way using an array of hashes and it works.

furniture = [
    {:name => "bed", :color => "black", :size => "12", :date_created => "12/6", :condition => "New"},
    {:name => "chair", :color => "brown", :size => "7", :date_created => "6/13", :condition => "Used"},
    {:name => "desk", :color => "maple", :size => "9", :date_created => "2/13", :condition => "New"}]
furniture.each do |h|
    p h[:name]
    p h[:color]
    p h[:size]   
    p h[:date_created]
    p h[:condition]
end
