### ISSUE TITLE
Possible to register multiple apps with same name

### ISSUE THREAD

**Issue by dariusk** [tootsuite/mastodon-api#4]
I've confirmed that I can register two apps with the same name on the same instance via Oauth:

![screenshot](http://tinysubversions.com/pics/dualregister.png)

This probably should be prevented in order to keep people from spoofing other apps, though I'm no security expert so maybe this isn't an issue at all.

**Comment by muffinista** [comment]
I've been toying with making it possible to add an app and/or display oauth tokens within the preferences section and I noticed this issue as well. It looks like this was an explicit choice based on https://github.com/tootsuite/mastodon/issues/45

At first it seemed strange to me, but in the context of a distributed platform I can see how it makes sense? Regardless, I think it's an issue with mastodon itself.

**Comment by Gargron** [comment]
Indeed, this is not a bug.
