### ISSUE TITLE
create_account returns Mastodon::Error::UnprocessableEntity

### ISSUE THREAD

**Issue by mvalenzisiAK** [tootsuite/mastodon-api#42]
Hi,

I am trying to create a user with the create_user method. I followed this instructions to get the token: https://gist.github.com/aparrish/661fca5ce7b4882a8c6823db12d42d26

When I call the method create_user I get the following error:

/home/mau/.gem/ruby/2.4.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/request.rb:32:in `fail_or_return': Mastodon::Error::UnprocessableEntity (Mastodon::Error::UnprocessableEntity)
	from /home/mau/.gem/ruby/2.4.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/request.rb:26:in `perform'
	from /home/mau/.gem/ruby/2.4.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/utils.rb:10:in `perform_request'
	from /home/mau/.gem/ruby/2.4.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/utils.rb:18:in `perform_request_with_object'
	from /home/mau/.gem/ruby/2.4.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/accounts.rb:72:in `create_account'
	from create-user.rb:30:in `<main>'

The token has read and write access.

**Comment by Gargron** [comment]
Can you catch the exception and print it as a string?

```ruby
begin
   ...
rescue Mastodon::Error::ClientError => e
  puts e.to_s
end
```

Because the reason must be in the body returned by the server.

**Comment by mvalenzisiAK** [comment]
That is the call:

```
begin
  access_token = mastodon_client.create_account(account)
rescue Mastodon::Error::ClientError => e
  puts e.to_s
end
```
and I get this error:
```
Mastodon::Error::UnprocessableEntity
create-user.rb:36:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by Gargron** [comment]
Hmm, looks like a bug in the error class, huh. At least, it seems like the JSON returned by the server is missing, so the error class trying to use the `error` attribute from the response fails.

Just as a side note, what version is the Mastodon server you are connecting to?

**Comment by mvalenzisiAK** [comment]
I'm running `v2.6.5`

**Comment by Gargron** [comment]
The endpoint is available since 2.7.0: https://docs.joinmastodon.org/api/rest/accounts/#resource-information-1

**Comment by mvalenzisiAK** [comment]
Oh, that explains a lot. I will upgrade and try it out. Thanks!

**Comment by mvalenzisiAK** [comment]
I confirm, upgraded to `v2.7.3` and it works.
Thanks again!
