### ISSUE TITLE
[Bug] `can't modify frozen String: ""`

### ISSUE THREAD

**Issue by ghost** [tootsuite/mastodon-api#55]
There is a bug in the `Mastodon::REST::Client#create_status` method that results in an exception being raised ***after*** the status is posted. Below is a formatted stack trace of where the exception is being raised:

```
can't modify frozen String: ""
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-3.3.0/lib/http/response/body.rb:52:in `force_encoding'
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-3.3.0/lib/http/response/body.rb:52:in `to_s'
    at C:/Ruby32-x64/lib/ruby/3.2.0/forwardable.rb:234:in `empty?'
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/request.rb:26:in `perform'
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/utils.rb:10:in `perform_request'
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/utils.rb:18:in `perform_request_with_object'
    at C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mastodon-api-2.0.0/lib/mastodon/rest/statuses.rb:24:in `create_status'
    at C:/Users/<USER-ID>/mastodon-joke-bot/src/jokes.rb:32:in `send_to'
    at C:/Users/<USER-ID>/mastodon-joke-bot/src/main.rb:33:in `start'
    at main.rb:5:in `<main>'
```

To reproduce the error:
1. clone [this repository](https://github.com/IRod22/mastodon-joke-bot) and have `bundler install` the dependencies;
2. with your Mastodon account, create an application with `write` access and have the access token ready for the next step;
3. copy and rename `src/env.example.rb` to `src/env.rb` **and** fill in the `:DOMAIN` and `:TOKEN` variables with your server's URL and access token.;
4. Run the following in the command line:
   ```
   ~/path/to/cloned/repo $ ruby main.rb
   ```
   and
5. enter `y` or `yes`.

The error should be visible when the program starts to create the status (after `Sending joke now...`).

**Comment by kevintraver** [comment]
This is actually an issue because of the `http` gem. See: https://github.com/httprb/http/issues/640

Looks like there is already open PR: https://github.com/mastodon/mastodon-api/pull/53

For now you could try installing this gem from source.

**Comment by ghost** [comment]
Thank you, @kevintraver. I'm closing this issue.
